name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build the application
      run: npm run build

    - name: Deploy to VPS
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        scp -r ./* $VPS_USER@$VPS_HOST:$DEPLOY_PATH
        ssh $VPS_USER@$VPS_HOST << EOF
          cd $DEPLOY_PATH
          npm install --production
          pm2 stop mateus-dev-me.com.br || true
          pm2 start ecosystem.config.js
          pm2 save
        EOF
