name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh $VPS_USER@$VPS_HOST << EOF
            cd $DEPLOY_PATH
            git pull origin master
            npm install --production
            pm2 stop mateus-dev-me.com.br || true
            pm2 start ecosystem.config.js --only mateus-dev-me.com.br
            pm2 save
          EOF
